project_name: "VQ-VAE Steamboat Willie"
paths:
- /content/drive/My Drive/SteamboatWillie/SteamboatWillie.mp4
dest_dir: ./clips/
checkpoint_path: ./checkpoints
save_top_k: 1
train_split: 0.8
batch_size: 8
max_epochs: 120
training_steps: 100000
num_workers: 2
lr: 0.0003
beta1: 0.9
beta2: 0.999
weight_decay: 0.0
use_wd_schedule: false
use_lr_schedule: false
clip_length: 16
img_size: 256
in_channels: 1
latent_channels: 16
codebook_size: 1024
commit_loss_beta: 0.25
track_codebook: true
use_ema: true
ema_gamma: 0.99
hidden_channels: 256
nblocks: 1
nlayers: 4