encoder:
  in_channels: 1
  out_channels: 5
  init_channels: 64
  channel_multipliers: [1, 2, 2, 4]
  num_downsamples: 3
  num_space_downsamples: 3
  num_time_downsamples: 2
  num_res_blocks: 1
  causal: false
decoder:
  in_channels: 5
  out_channels: 1
  init_channels: 64
  channel_multipliers: [1, 2, 2, 4]
  num_upsamples: 3
  num_space_upsamples: 3
  num_time_upsamples: 2
  num_res_blocks: 1
  causal: false
loss:
  recon_loss_type: mse
  aux_losses:
    perceptual:
      weight: 0.1